- hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: Update software cache
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install software
    ansible.builtin.apt: 
      pkg:
        - python3-pip
        - python3-docker
      state: present
    become: true