- hosts: all
  gather_facts: yes
  remote_user: root

  tasks:
  - name: update apt-cache
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: apt install
    ansible.builtin.apt: 
      pkg:
        - python3-pip
        - python3-docker
      state: present
    become: true

  - name: docker run
    community.docker.docker_container:
      name: redmine
      image: redmine
      published_ports: 3000:3000
      restart_policy: always
      restart: yes
      container_default_behavior: no_defaults
      env:
        REDMINE_DB_DATABASE: "{{ DB_NAME }}"
        REDMINE_DB_POSTGRES: "{{ DB_HOST }}"
        REDMINE_DB_PORT: "{{ DB_PORT }}"
        REDMINE_DB_USERNAME: "{{ DB_USERNAME }}"
        REDMINE_DB_PASSWORD: "{{ DB_PASSWORD }}"


- hosts: webservers
  gather_facts: yes
  remote_user: root
  roles:
    - { role: datadog.datadog, become: yes }