- hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: Update software cache
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400
    tags: install

  - name: Install software
    ansible.builtin.apt: 
      pkg:
        - python3-pip
        - python3-docker
      state: present
    become: true
    tags: install

  - name: Run application
    community.docker.docker_container:
      name: redmine
      image: redmine
      published_ports: 3000:3000
      restart_policy: always
      restart: yes
      container_default_behavior: no_defaults
      env:
        REDMINE_DB_DATABASE: "{{ db_name }}"
        REDMINE_DB_POSTGRES: "{{ db_host }}"
        REDMINE_DB_PORT: "{{ db_port }}"
        REDMINE_DB_USERNAME: "{{ db_username }}"
        REDMINE_DB_PASSWORD: "{{ db_password }}"
    tags: deploy


- hosts: webservers
  remote_user: "{{ remote_user }}"

  tasks:
  - name: Run monitoring
    ansible.builtin.include_role:
      name: datadog.datadog
    tags: deploy